
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-005-build
  labels:
    app : app-005
    team: acme-idp-001
    build-namespace: app-005-build
    size: small
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: app-005-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-005-dev
  labels:
    app : app-005
    team: acme-idp-001
    build-namespace: app-005-build
    size: small
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: app-005-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-005-qa
  labels:
    app : app-005
    team: acme-idp-001
    build-namespace: app-005-build
    size: small
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: app-005-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-005-prod
  labels:
    app : app-005
    team: acme-idp-001
    build-namespace: app-005-build
    size: small
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: app-005-build
